- hosts: "masters, workers"
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: destroy the cluster
      shell: kubeadm reset --force